import { StyleSheet, Platform, StatusBar } from "react-native";
import { COLORS, FONTS } from "@/styles/theme";

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F2F3F5" },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 14,
    paddingTop:
      Platform.OS === "android" ? (StatusBar.currentHeight || 0) + 10 : 10,
    backgroundColor: "#D8F1F3",
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.7)",
  },
  headerTitle: {
    fontFamily: FONTS.bold,
    fontSize: 20,
    color: COLORS.textPrimary,
    flex: 1,
    marginLeft: 10,
  },
  refreshBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.7)",
    justifyContent: "center",
    alignItems: "center",
  },

  scroll: { padding: 16 },

  // Summary
  summaryCard: {
    backgroundColor: COLORS.primary,
    borderRadius: 20,
    padding: 24,
    marginBottom: 14,
    alignItems: "center",
  },
  summaryLabel: {
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: "rgba(255,255,255,0.8)",
    marginBottom: 6,
  },
  summaryAmount: { fontFamily: FONTS.bold, fontSize: 34, color: COLORS.white },
  summaryCustomer: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "rgba(255,255,255,0.85)",
    marginTop: 8,
  },

  // Success
  successBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: "#ECFDF5",
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#6EE7B7",
  },
  successTitle: { fontFamily: FONTS.bold, fontSize: 16, color: "#065F46" },
  successSub: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#059669",
    marginTop: 2,
  },

  // Card
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  cardTitle: {
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: COLORS.textPrimary,
    marginBottom: 14,
  },

  // Method Buttons
  methodBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 14,
    borderRadius: 14,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
  },
  methodBtnActive: { borderColor: COLORS.primary, backgroundColor: "#FFF7F0" },
  methodIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  methodIconActive: { backgroundColor: COLORS.primary },
  methodInfo: { flex: 1 },
  methodTitle: {
    fontFamily: FONTS.semiBold,
    fontSize: 15,
    color: COLORS.textPrimary,
  },
  methodTitleActive: { color: COLORS.primary },
  methodDesc: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.textMuted,
    marginTop: 2,
  },
  methodRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#D1D5DB",
    justifyContent: "center",
    alignItems: "center",
  },
  methodRadioActive: { borderColor: COLORS.primary },
  methodRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.primary,
  },

  ttsNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    backgroundColor: "#FFF7F0",
    borderRadius: 10,
    padding: 10,
    marginTop: 4,
  },
  ttsNoteText: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.primary,
    flex: 1,
  },

  // Cash Input
  cashInputCard: {
    backgroundColor: "#FFFBF5",
    borderRadius: 14,
    padding: 16,
    marginTop: 8,
    borderWidth: 1.5,
    borderColor: COLORS.primary + "40",
  },
  cashInputLabel: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: COLORS.textMuted,
    marginBottom: 4,
  },
  cashInputTotal: {
    fontFamily: FONTS.bold,
    fontSize: 22,
    color: COLORS.primary,
    marginBottom: 14,
  },
  cashInput: {
    height: 52,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    paddingHorizontal: 14,
    fontFamily: FONTS.semiBold,
    fontSize: 18,
    color: COLORS.textPrimary,
    backgroundColor: "#FFFFFF",
  },
  cashChangeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    backgroundColor: "#ECFDF5",
    borderRadius: 10,
    padding: 12,
  },
  cashChangeLabel: { fontFamily: FONTS.medium, fontSize: 13, color: "#065F46" },
  cashChangeValue: { fontFamily: FONTS.bold, fontSize: 16, color: "#065F46" },
  cashShortfall: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#991B1B",
    marginTop: 8,
  },

  // History
  emptyHistory: { alignItems: "center", paddingVertical: 24, gap: 8 },
  emptyHistoryText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: COLORS.textMuted,
  },
  historyItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: 12,
  },
  historyBorder: { borderBottomWidth: 1, borderBottomColor: "#F3F4F6" },
  historyLeft: { flex: 1 },
  historyRight: { alignItems: "flex-end", gap: 6 },
  historyMethod: {
    fontFamily: FONTS.semiBold,
    fontSize: 14,
    color: COLORS.textPrimary,
  },
  historyTime: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.textMuted,
    marginTop: 2,
  },
  historyTxn: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.textMuted,
    marginTop: 1,
  },
  historyAmount: {
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: COLORS.textPrimary,
  },
  payStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  payStatusText: { fontFamily: FONTS.semiBold, fontSize: 11 },

  // Footer
  footer: {
    padding: 16,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
    paddingBottom: Platform.OS === "ios" ? 30 : 16,
  },
  confirmBtn: {
    height: 56,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
  },
  confirmBtnText: { fontFamily: FONTS.bold, fontSize: 16, color: COLORS.white },

  // Done row: bill + back
  doneActions: { flexDirection: "row", gap: 10 },
  billBtn: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: COLORS.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#FFF7F0",
  },
  billBtnText: {
    fontFamily: FONTS.semiBold,
    fontSize: 14,
    color: COLORS.primary,
  },
  doneBtn: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    backgroundColor: COLORS.success,
    justifyContent: "center",
    alignItems: "center",
  },
  doneBtnText: { fontFamily: FONTS.bold, fontSize: 15, color: COLORS.white },

  // Bill Modal
  billModalContainer: { flex: 1, backgroundColor: "#F2F3F5" },
  billModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  billModalTitle: {
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: COLORS.textPrimary,
  },
  billModalClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  billModalScroll: { alignItems: "center", paddingVertical: 20 },
  billModalActions: {
    flexDirection: "row",
    gap: 12,
    padding: 16,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingBottom: Platform.OS === "ios" ? 30 : 16,
  },
  billActionBtn: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    elevation: 3,
  },
  billPrintBtn: { backgroundColor: COLORS.primary },
  billShareBtn: { backgroundColor: "#0B7F8C" },
  billActionText: { fontFamily: FONTS.semiBold, fontSize: 15, color: "#fff" },

  // VNPay confirm
  vnpayPendingNote: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFF7F0",
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
  },
  vnpayPendingText: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.primary,
    flex: 1,
  },
  vnpayConfirmBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    height: 56,
    borderRadius: 16,
    backgroundColor: COLORS.success,
    elevation: 4,
  },
});
